### PR TITLE
Add Java linter Github Action.

### PR DESCRIPTION
**Pull request by billyeh**
Trying to get a Java auto-linter running for your project :) Would you mind having the guinea pig repository?

### CODE REVIEW

**Comment by Obinnabii** [comment]
yeah sure haha.
How do I check if it's working?

**Review by Obinnabii — APPROVED** [review]
LGTM

**Comment by billyeh** [comment]
I had a successful run, with no Java files changed 😂 https://github.com/billyeh/my-portfolio/actions/runs/136295675/workflow. Let's see if it does anything next time we edit a Java file/maybe make a lint mistake.

**Comment by billyeh** [comment]
Oh wait. Check out all the files changed in this PR. It went and fixed all the Java files!! 🤩  This is amazing

**Comment by Obinnabii** [comment]
Oh yeah I just saw! that's so convenient! thanks man!
From what I read, it formats files on pushes right?

**Comment by billyeh** [comment]
Yep! Right now it runs on a push to any branch, figure that makes sense as any code we push will get linted right then :) Didn't really take a look at the free limits on Github Actions but we'll see if it causes issues.

**Comment by Obinnabii** [comment]
Yeah that's such a relief! I'll let you know if anything happens!

**Pull request merged**
